Repository YehaoO-chen/AgileWebDevGroup23, pull requests merged in 2025-05, with the labels that each got.

#47 Revert "Salted Hash the password and answer when created"
  .gitignore
  app/models.py
  app/routes.py
Labels: status:review

#49 hash password and security answer when create a new user
  app/models.py
  app/routes.py
Labels: enhancement, module:auth

#83 fix bug Uncaught ReferenceError: loadAndDisplayData is not defined, and change var declaration and remove studyplan title from model
  app/apis/studyplan.py
  app/models.py
  app/static/js/dashboard.js
  app/static/js/notification.js
  app/static/js/shareModal.js
  app/templates/dashboard.html
  app/templates/mainpage.html
  app/templates/notification.html
Labels: priority:high
